=== francescorosso/DP2/Assignment1/bin/dtd/cluster.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cluster (hosts,jobGroups,jobs?)>
<!ATTLIST cluster
	name CDATA #REQUIRED
	status (OK|UNAVAIL) #REQUIRED
	masterHost IDREF #IMPLIED
>

<!ELEMENT hosts (host*)>

<!ELEMENT host EMPTY>
<!ATTLIST host
	name ID #REQUIRED
	type (CLIENT|SERVER|MASTER) #REQUIRED
	status (OK|UNAVAIL|CLOSED|UNLICENSED) #REQUIRED
	load CDATA "0"
	memory CDATA "0"
>

<!ELEMENT jobGroups (jobGroup+)>

<!ELEMENT jobGroup EMPTY>
<!ATTLIST jobGroup
	name ID #REQUIRED
	description CDATA #IMPLIED
>

<!ELEMENT jobs (job*)>

<!ELEMENT job EMPTY>
<!ATTLIST job
	jobID ID #REQUIRED
	state (PENDING|RUNNING|DONE|EXIT|SUSPENDED) #REQUIRED
	submissionHost IDREF #REQUIRED
	submissionTime CDATA #REQUIRED
	jobGroup IDREF "default"
	executionHost IDREF #IMPLIED
>

=== francescorosso/DP2/Assignment1/src/dtd/cluster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cluster SYSTEM "cluster.dtd">

<cluster status="OK" name="testCluster" masterHost="node1">
	<hosts>
		<host name="node1" type="MASTER" status="OK" />
		<host name="node2" type="SERVER" status="OK" />
		<host name="client1" type="CLIENT" status="OK" />
	</hosts>
	<jobGroups>
		<jobGroup name="default" />
	</jobGroups>
	<jobs>
		<job jobID="_1" state="RUNNING" submissionHost="client1" submissionTime="1351095690242" executionHost="node2" />
	</jobs>
</cluster>
