=== francescorosso/DP2/Assignment4/xsd/PJSInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xsd:element name="cluster">
	<xsd:complexType>
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="hosts" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="host" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required" />
								<xsd:attribute name="type" use="required">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="MASTER" />
											<xsd:enumeration value="SERVER" />
											<xsd:enumeration value="CLIENT" />
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
								<xsd:attribute name="status" use="required">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="OK" />
											<xsd:enumeration value="UNAVAIL" />
											<xsd:enumeration value="CLOSED" />
											<xsd:enumeration value="UNLICENSED" />
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
								<xsd:attribute name="load" type="xsd:int" use="optional" default="0" />
								<xsd:attribute name="memory" type="xsd:int" use="optional" default="0" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="jobGroups" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="jobGroup" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:ID" use="required" />
								<xsd:attribute name="description" type="xsd:string" use="optional" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="jobs" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="job" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="jobID" type="xsd:string" use="required" />
								<xsd:attribute name="state" use="required" >
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:enumeration value="PENDING" />
											<xsd:enumeration value="RUNNING" />
											<xsd:enumeration value="DONE" />
											<xsd:enumeration value="EXIT" />
											<xsd:enumeration value="SUSPENDED" />
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
								<xsd:attribute name="submissionHost" type="xsd:string" use="required" />
								<xsd:attribute name="submissionTime" type="xsd:long" use="required" />
								<xsd:attribute name="jobGroup" type="xsd:string" use="optional" default="default" />
								<xsd:attribute name="executionHost" type="xsd:string" use="optional" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="masterHost" type="xsd:string" />
		<xsd:attribute name="status">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="OK" />
					<xsd:enumeration value="UNAVAIL" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:key name="hostNameKey">
		<xsd:selector xpath="hosts/host" />
		<xsd:field xpath="@name"></xsd:field>
	</xsd:key>
	<xsd:key name="jobGroupNameKey">
		<xsd:selector xpath="jobGroups/jobGroup" />
		<xsd:field xpath="@name" />
	</xsd:key>
	<xsd:keyref name="masterHostKeyref" refer="hostNameKey">
		<xsd:selector xpath="." />
		<xsd:field xpath="@masterHost" />
	</xsd:keyref>
	<xsd:keyref name="submissionHostKeyref" refer="hostNameKey">
		<xsd:selector xpath="jobs/job" />
		<xsd:field xpath="@submissionHost" />
	</xsd:keyref>
	<xsd:keyref name="executionHostKeyref" refer="hostNameKey">
		<xsd:selector xpath="jobs/job" />
		<xsd:field xpath="@executionHost" />
	</xsd:keyref>
	<xsd:keyref name="jobGroupKeyref" refer="jobGroupNameKey">
		<xsd:selector xpath="jobs/job" />
		<xsd:field xpath="@jobGroup" />
	</xsd:keyref>
</xsd:element>

</xsd:schema>

=== francescorosso/DP2/Assignment4/xsd/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" status="OK" masterHost="host25" name="PJSCluster" xsi:noNamespaceSchemaLocation="PJSInfo.xsd">
    <hosts>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host27"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host13"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host10"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host22"/>
        <host memory="4096" load="0" status="OK" type="SERVER" name="host20"/>
        <host memory="256" load="0" status="OK" type="SERVER" name="host16"/>
        <host memory="256" load="0" status="OK" type="SERVER" name="host1"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host4"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host29"/>
        <host memory="2048" load="0" status="OK" type="SERVER" name="host30"/>
        <host memory="-1" load="-1" status="UNAVAIL" type="SERVER" name="host18"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host7"/>
        <host memory="4096" load="0" status="OK" type="SERVER" name="host14"/>
        <host memory="1024" load="0" status="OK" type="MASTER" name="host25"/>
        <host memory="256" load="0" status="OK" type="SERVER" name="host33"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host24"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host31"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host0"/>
        <host memory="512" load="0" status="OK" type="SERVER" name="host12"/>
        <host memory="512" load="0" status="OK" type="SERVER" name="host34"/>
        <host memory="512" load="0" status="OK" type="SERVER" name="host6"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host11"/>
        <host memory="4096" load="0" status="OK" type="SERVER" name="host3"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host5"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host9"/>
        <host memory="2048" load="0" status="OK" type="SERVER" name="host28"/>
        <host memory="-1" load="-1" status="UNAVAIL" type="SERVER" name="host26"/>
        <host memory="-1" load="-1" status="OK" type="CLIENT" name="host21"/>
        <host memory="2048" load="0" status="OK" type="SERVER" name="host2"/>
        <host memory="1024" load="0" status="OK" type="SERVER" name="host8"/>
        <host memory="-1" load="-1" status="UNAVAIL" type="SERVER" name="host19"/>
        <host memory="256" load="0" status="OK" type="SERVER" name="host15"/>
        <host memory="2048" load="0" status="OK" type="SERVER" name="host17"/>
        <host memory="-1" load="-1" status="UNAVAIL" type="SERVER" name="host23"/>
        <host memory="2048" load="0" status="OK" type="SERVER" name="host32"/>
    </hosts>
    <jobGroups>
        <jobGroup description="This is the 'default' group." name="default"/>
    </jobGroups>
    <jobs/>
</cluster>

=== francescorosso/DP2/Assignment3/src/xsd/PJSInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PJSInfo.xsd"
	status="OK" name="testCluster" masterHost="node1">
	<hosts>
		<host name="node1" type="MASTER" status="OK" />
		<host name="node2" type="SERVER" status="OK" />
		<host name="client1" type="CLIENT" status="OK" />
	</hosts>
	<jobGroups>
		<jobGroup name="default"/>
	</jobGroups>
	<jobs>
		<job submissionHost="client1" submissionTime="1351095690242" state="PENDING" jobID="_1" />
	</jobs>
</cluster>
